# Generated by Django 4.0.3 on 2022-12-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reciperequirement_unit_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='unit',
        ),
    ]
