# Generated by Django 4.0.3 on 2022-12-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_reciperequirement_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='menu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='inventory.menuitem'),
        ),
    ]
